#pragma once

#define UP_STRING "Up"
#define DOWN_STRING "Down"
#define LEFT_STRING "Left"
#define RIGHT_STRING "Right"
#define IF_STRING "If"
#define ELSE_STRING	"Else"
#define WHILE_STRING "While"
#define END_STRING "End"
#define THEN_STRING "Then"
#define IUP_STRING "iUp"
#define IDOWN_STRING "iDown"
#define ILEFT_STRING "iLeft"
#define IRIGHT_STRING "iRight"
#define BARRIER_STRING "Wall"
#define LOOSE_STRING "Loose"
#define AND_STRING "And"
#define OR_STRING "Or"
#define EMPTY_STRING  "Empty"

#define UP_LOW_RUS_STRING "вверх"
#define DOWN_LOW_RUS_STRING	"вниз"
#define LEFT_LOW_RUS_STRING	"влево"
#define RIGHT_LOW_RUS_STRING "вправо"
#define IF_LOW_RUS_STRING "если"
#define ELSE_LOW_RUS_STRING	"иначе"
#define WHILE_LOW_RUS_STRING "пока"
#define END_LOW_RUS_STRING "конец"
#define THEN_LOW_RUS_STRING	"то"
#define IUP_LOW_RUS_STRING	"вверху"
#define IDOWN_LOW_RUS_STRING "внизу"
#define ILEFT_LOW_RUS_STRING "слева"
#define IRIGHT_LOW_RUS_STRING "справа"
#define BARRIER_LOW_RUS_STRING "стена"
#define LOOSE_LOW_RUS_STRING "свободно"
#define AND_LOW_RUS_STRING "и"
#define OR_LOW_RUS_STRING "или"

#define UP_UP_RUS_STRING "Вверх"
#define DOWN_UP_RUS_STRING	"Вниз"
#define LEFT_UP_RUS_STRING	"Влево"
#define RIGHT_UP_RUS_STRING "Вправо"
#define IF_UP_RUS_STRING "Если"
#define ELSE_UP_RUS_STRING	"Иначе"
#define WHILE_UP_RUS_STRING "Пока"
#define END_UP_RUS_STRING "Конец"
#define THEN_UP_RUS_STRING	"То"
#define IUP_UP_RUS_STRING	"Вверху"
#define IDOWN_UP_RUS_STRING "Внизу"
#define ILEFT_UP_RUS_STRING "Слева"
#define IRIGHT_UP_RUS_STRING "Справа"
#define BARRIER_UP_RUS_STRING "Стена"
#define LOOSE_UP_RUS_STRING "Свободно"
#define AND_UP_RUS_STRING "И"
#define OR_UP_RUS_STRING "Или"

#define STOP_WORD "ALL"